#!/usr/bin/env python3
import os
import ssl
from pathlib import Path

from werkzeug.serving import make_ssl_devcert

from backend.app import create_app


app = create_app()


def _build_tls_context() -> ssl.SSLContext:
    """
    Build and configure SSL/TLS context for the Flask server.
    
    Certificate Generation Process:
    --------------------------------
    PRODUCTION (with CA-signed certificates):
      1. Obtain TLS certificate from a trusted Certificate Authority (CA)
         - Recommended: Let's Encrypt (https://letsencrypt.org/)
         - Alternative: Commercial CA (DigiCert, GlobalSign, etc.)
      2. Set environment variables:
         export TLS_CERT_FILE=/path/to/your_cert.pem
         export TLS_KEY_FILE=/path/to/your_key.pem
      3. Certificate chain should include intermediate certificates if needed
      
    DEVELOPMENT (auto-generated self-signed certificate):
      1. If TLS_CERT_FILE/TLS_KEY_FILE not set, Werkzeug generates cert automatically
      2. Default location: .tls/dev-cert.crt and .tls/dev-cert.key
      3. Generated by werkzeug.make_ssl_devcert() function
      4. Certificate info:
         - Subject CN: localhost
         - Algorithm: RSA 2048-bit
         - Validity: 10 years (default)
         - Not CA-signed (self-signed, for dev only!)
      
    Security Configuration:
      - Minimum TLS version: 1.2
      - Strong cipher suites: AES-GCM, CHACHA20-POLY1305
      - Server cipher preference enabled
      - SSLv2/v3 disabled
      - Compression disabled (CRIME attack prevention)
      - Session tickets disabled
   
    Returns:
        ssl.SSLContext: Configured SSL context ready for use with Flask
    """
    cert_file = os.environ.get("TLS_CERT_FILE")
    key_file = os.environ.get("TLS_KEY_FILE")
    
    if cert_file and key_file:
        ctx = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)
        ctx.minimum_version = ssl.TLSVersion.TLSv1_2
        ctx.load_cert_chain(certfile=cert_file, keyfile=key_file)
        
        ctx.set_ciphers(
            "ECDHE-ECDSA-AES128-GCM-SHA256:"
            "ECDHE-RSA-AES128-GCM-SHA256:"
            "ECDHE-ECDSA-AES256-GCM-SHA384:"
            "ECDHE-RSA-AES256-GCM-SHA384:"
            "ECDHE-ECDSA-CHACHA20-POLY1305:"
            "ECDHE-RSA-CHACHA20-POLY1305:"
            "DHE-RSA-AES128-GCM-SHA256:"
            "DHE-RSA-AES256-GCM-SHA384"
        )
        
        ctx.options |= ssl.OP_CIPHER_SERVER_PREFERENCE
        ctx.options |= ssl.OP_NO_SSLv2
        ctx.options |= ssl.OP_NO_SSLv3
        ctx.options |= ssl.OP_NO_COMPRESSION
        ctx.options |= ssl.OP_NO_TICKET
        return ctx

    cert_base = Path(os.environ.get("TLS_DEV_CERT_BASE", ".tls/dev-cert"))
    cert_path = cert_base.with_suffix(".crt")
    key_path = cert_base.with_suffix(".key")
    cert_path.parent.mkdir(parents=True, exist_ok=True)
    
    if not cert_path.exists() or not key_path.exists():
        make_ssl_devcert(str(cert_base), host="localhost")

    ctx = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)
    ctx.minimum_version = ssl.TLSVersion.TLSv1_2
    ctx.load_cert_chain(certfile=str(cert_path), keyfile=str(key_path))
    
    ctx.set_ciphers(
        "ECDHE-ECDSA-AES128-GCM-SHA256:"
        "ECDHE-RSA-AES128-GCM-SHA256:"
        "ECDHE-ECDSA-AES256-GCM-SHA384:"
        "ECDHE-RSA-AES256-GCM-SHA384:"
        "ECDHE-ECDSA-CHACHA20-POLY1305:"
        "ECDHE-RSA-CHACHA20-POLY1305:"
        "DHE-RSA-AES128-GCM-SHA256:"
        "DHE-RSA-AES256-GCM-SHA384"
    )
    
    ctx.options |= ssl.OP_CIPHER_SERVER_PREFERENCE
    ctx.options |= ssl.OP_NO_SSLv2
    ctx.options |= ssl.OP_NO_SSLv3
    ctx.options |= ssl.OP_NO_COMPRESSION
    ctx.options |= ssl.OP_NO_TICKET
    
    return ctx


if __name__ == "__main__":
    app.run(host="0.0.0.0", port=8765, debug=True, ssl_context=_build_tls_context())
