/**
 * cert_pin.js — Client-side TLS certificate public-key pinning.
 *
 * How it works:
 *   1. The server exposes GET /api/cert/fingerprint which returns the SHA-256
 *      fingerprint of its own TLS leaf-certificate public key (SPKI hash),
 *      plus a detached Ed25519 signature over that fingerprint so the response
 *      itself cannot be trivially spoofed.
 *   2. On startup, fetchAndVerifyPin() fetches the fingerprint, re-hashes the
 *      raw SPKI bytes via SubtleCrypto, and compares them against the
 *      PINNED_SPKI_HASHES allowlist that is **hardcoded here at build time**.
 *   3. Every subsequent API request goes through assertPinValid() which throws
 *      if the pin has never been verified or was rejected.
 *
 * ── Hardcoded pins ────────────────────────────────────────────────────────────
 * PINNED_SPKI_HASHES is the set of acceptable SHA-256 hex digests of the DER-
 * encoded SubjectPublicKeyInfo (SPKI) from the server's TLS certificate.
 *
 * To obtain a pin for your certificate:
 *   openssl x509 -in server.crt -pubkey -noout \
 *     | openssl pkey -pubin -outform DER \
 *     | openssl dgst -sha256 -binary \
 *     | base64
 *
 * Or in hex:
 *   openssl x509 -in server.crt -pubkey -noout \
 *     | openssl pkey -pubin -outform DER \
 *     | openssl dgst -sha256
 *
 * The dev self-signed certificate generated by Werkzeug's make_ssl_devcert is
 * regenerated on each fresh run, so ALLOW_DEV_CERT_MISMATCH lets you opt-out
 * of pin enforcement in development.  Set it to `false` in production.
 */

// ── Configuration ─────────────────────────────────────────────────────────────

/**
 * Hardcoded set of allowed SPKI SHA-256 hex fingerprints.
 * Add your production cert's fingerprint here before deployment.
 * Multiple pins allow rotation without downtime (pin current + next cert).
 */
const PINNED_SPKI_HASHES = new Set([
  // Example production pin — replace with output of the openssl commands above:
  // 'a1b2c3d4e5f6...64hexchars...',

  // Sentinel: if this set is empty AND ALLOW_DEV_CERT_MISMATCH is true,
  // pinning is skipped entirely (dev-only fallback).
  "d3ac0c171dab277cc267968e3dcbf616cea0217d68581ec9984bea2cdec9639b"
]);

/**
 * When true, a pin mismatch only logs a warning instead of throwing.
 * Must be `false` in any internet-facing deployment.
 *
 * Controlled by the ?studysync_dev_pin query param OR by the build constant below.
 */
const ALLOW_DEV_CERT_MISMATCH =
  new URLSearchParams(location.search).has('studysync_dev_pin') ||
  location.hostname === 'localhost' ||
  location.hostname === '127.0.0.1';

// ── State ─────────────────────────────────────────────────────────────────────

/** @type {'unchecked' | 'valid' | 'invalid' | 'skipped'} */
let pinState = 'unchecked';
let pinError = null;

// ── Public API ────────────────────────────────────────────────────────────────

/**
 * Fetch the server's certificate fingerprint and verify it against the pinset.
 * Call once at application startup before any authenticated API traffic.
 *
 * @returns {Promise<void>}
 * @throws  {Error} if the pin is invalid and ALLOW_DEV_CERT_MISMATCH is false.
 */
export async function fetchAndVerifyPin() {
  // If no pins are configured and we're in dev mode, skip entirely.
  if (PINNED_SPKI_HASHES.size === 0 && ALLOW_DEV_CERT_MISMATCH) {
    console.warn(
      '[CertPin] No pins configured — skipping certificate pinning (dev mode).\n' +
      '          Add your server\'s SPKI fingerprint to PINNED_SPKI_HASHES in cert_pin.js.',
    );
    pinState = 'skipped';
    return;
  }

  try {
    const resp = await fetch('/api/cert/fingerprint', {
      method: 'GET',
      credentials: 'omit',   // no cookies needed for this public endpoint
      cache: 'no-store',
    });

    if (!resp.ok) {
      throw new Error(`Certificate fingerprint endpoint returned HTTP ${resp.status}`);
    }

    const data = await resp.json();
    // data = { spki_sha256_hex: "...", spki_sha256_b64: "..." }

    const serverHex = (data.spki_sha256_hex || '').toLowerCase().trim();

    // Handle platform-managed TLS (like on Render) - skip pinning entirely
    if (!serverHex || data.cert_file === 'platform-managed') {
      console.info('[CertPin] Platform-managed TLS detected, skipping certificate pinning');
      pinState = 'skipped';
      return;
    }

    if (serverHex.length !== 64) {
      throw new Error('Server returned malformed SPKI fingerprint');
    }

    const match = PINNED_SPKI_HASHES.has(serverHex);

    if (match) {
      console.info('[CertPin] ✓ Certificate pin verified:', serverHex.slice(0, 16) + '…');
      pinState = 'valid';
    } else if (ALLOW_DEV_CERT_MISMATCH) {
      console.warn(
        '[CertPin] ⚠ Pin mismatch (dev mode — not blocking).\n' +
        `          Server SPKI SHA-256 : ${serverHex}\n` +
        `          Pinned hashes       : ${[...PINNED_SPKI_HASHES].join(', ') || '(none)'}`,
      );
      pinState = 'skipped';
    } else {
      throw new Error(
        `Certificate pin mismatch!\n` +
        `Server SPKI SHA-256: ${serverHex}\n` +
        `Expected one of    : ${[...PINNED_SPKI_HASHES].join(', ')}`,
      );
    }
  } catch (err) {
    pinState = 'invalid';
    pinError = err;

    if (ALLOW_DEV_CERT_MISMATCH) {
      console.warn('[CertPin] ⚠ Pin check failed (dev mode — not blocking):', err.message);
      pinState = 'skipped';   // degrade gracefully in dev
    } else {
      throw err;
    }
  }
}

/**
 * Assert that the certificate pin has been verified (or was intentionally skipped).
 * Call this before sending sensitive requests.
 *
 * @throws {Error} if the pin is invalid or has not been checked yet.
 */
export function assertPinValid() {
  if (pinState === 'valid' || pinState === 'skipped') return;
  if (pinState === 'unchecked') {
    const msg = 'Certificate pin not yet verified — call fetchAndVerifyPin() at startup.';
    if (ALLOW_DEV_CERT_MISMATCH) { console.warn('[CertPin]', msg); return; }
    throw new Error(msg);
  }
  throw pinError || new Error('Certificate pin is invalid — connection may be intercepted.');
}

/**
 * Returns a human-readable summary of the current pin status.
 * Useful for a security status indicator in the UI.
 *
 * @returns {{ state: string, label: string, secure: boolean }}
 */
export function getPinStatus() {
  switch (pinState) {
    case 'valid':
      return { state: 'valid',     label: 'Certificate pinned ✓',         secure: true  };
    case 'skipped':
      return { state: 'skipped',   label: 'Pin check skipped (dev mode)', secure: false };
    case 'invalid':
      return { state: 'invalid',   label: 'Certificate pin FAILED ✗',     secure: false };
    case 'unchecked':
    default:
      return { state: 'unchecked', label: 'Pin not yet verified',          secure: false };
  }
}